---
title: "about"
author: "Ricardo Barros"
date: '2022-08-15'
output: html_document
runtime: shiny
---

# Tree-life
Tree-life is an [open source](https://github.com/ricardovobarros/tree-life) web application written in R, developed to support intuitions in tracking reforested trees. The input is a log with the dates where the trees were planted and cut. The trees are identified by a GPS coordinate and ID. The app displays the following plots in order from top to bottom:

+ __Positioning Map__ displays the living and dead trees from the date of first log of the input dataset until the end date given by the user. 

+ __histogram__ shows the total number of the living and dead trees within their age in months of life or downed-age, respectively. 

+ __cumulative curve__ displays the sum of planted and downed trees between dates given as input by the user. 
 

### Why?

Planting trees and tracking their removal is common practice for many organizations. For example, a non-governmental organization may have the goal of reforesting in a protected area where illegal logging is taking place, or a paper industry may want to ensure the positive balance of its stock of remaining trees and their age. Tree-life can meet both exemplary requirements.


### Example

The example shown at the beginning of the application was inspired by the work of the NGO [Fairventures](https://fairventures.earth/). By 2020, the NGO has reached the mark of one million trees planted in Indonesia. Workers involved in the project can use a mobile app, also developed by [Fairventure](https://treeo.one/lang/en/about-us), to monitor deforestation and tree CO2 consumption over time.

Tanjung Puting National Park (region exemplified by Tree-life) is a national park in Indonesia in the Indonesian province of Central Kalimantan (Central Borneo), known for protecting orangutans. In recent years, the park has been heavily deforested due to logging and mining activities.


### Additional Information

+ [GitHub repository](https://github.com/ricardovobarros/tree-life)
+ [Ricardo Barros Portfolio](https://ricardovobarros.github.io/)
+ [Contact me](<mailto:ricardovobarros@live.com>)

__[COPY RIGHT](https://github.com/ricardovobarros/tree-life/blob/main/LICENSE) Ricardo Barros 2022__


